/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef CLOUDBUILDERMARMALADE_AUTODEFS_H
#define CLOUDBUILDERMARMALADE_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_CLOUDBUILDERMARMALADE_NAME "CloudBuilderMarmalade"
#define S3E_EXT_CLOUDBUILDERMARMALADE_HASH 0xbd728b87

#endif /* !CLOUDBUILDERMARMALADE_AUTODEFS_H */
